version: '2'
services:
  mongo-database:
    image: "mongo"
    ports:
     - "27017:27017"
  express-server:
    build: ./gc-server/
    ports:
      - "4000:4000"
    volumes:
      - ./gc-server:/usr/src/app
    depends_on:
      - mongo-database
  react-client:
    build: ./gc-client/
    ports:
      - "3000:3000"
    volumes:
      - ./gc-client:/usr/src/app
    depends_on:
      - express-server